#pragma once

#include "NativeGameplayTags.h"

namespace FTAGameplayTags
{
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Dash);

	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Light_Attack1);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Light_Attack2);

	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Grounded_Dash);



	
}
	