#pragma once

#include "NativeGameplayTags.h"

namespace FTAGameplayTags
{
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Dash);

	
}
	