#pragma once

#include "NativeGameplayTags.h"

namespace FTAGameplayTags
{
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Move);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Look);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Look_Mouse);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Look_Stick);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Ability_Jump);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Ability_Dash);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Ability_LightAttack);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold_Ability_LightAttack);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pressed_Ability_HeavyAttack);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold_Ability_HeavyAttack);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityTag_Movement_Jump);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Grounded_Dash);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Light_Attack1);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Light_Attack2);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Heavy_Attack1);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Grounded_Heavy_Attack2);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Aerial_Light_Attack1);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Symmetry_Aerial_Light_Attack2);
	//
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Calamity_Grounded_Light_Attack1);
	// FROMTHEASHESREBORN_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Weapon_Calamity_Grounded_Light_Attack2);
	
}
	